-- +goose Up
INSERT INTO currencies (code, name, symbol, decimal_places) VALUES
('AFN', 'Afghan Afghani', '؋', 2),
('ALL', 'Albanian Lek', 'Lek', 2),
('DZD', 'Algerian Dinar', 'دج', 2),
('AOA', 'Angolan Kwanza', 'Kz', 2),
('ARS', 'Argentine Peso', '$', 2),
('AMD', 'Armenian Dram', 'դր', 2),
('AUD', 'Australian Dollar', '$', 2),
('AZN', 'Azerbaijani Manat', '₼', 2),
('BSD', 'Bahamian Dollar', '$', 2),
('BHD', 'Bahraini Dinar', '.د.ب', 3),
('BDT', 'Bangladeshi Taka', '৳', 2),
('BBD', 'Barbados Dollar', '$', 2),
('BYN', 'Belarusian Ruble', 'Br', 2),
('BZD', 'Belize Dollar', 'BZ$', 2),
('BTN', 'Bhutanese Ngultrum', 'Nu.', 2),
('BOB', 'Bolivian Boliviano', '$b', 2),
('BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM', 2),
('BWP', 'Botswana Pula', 'P', 2),
('BRL', 'Brazilian Real', 'R$', 2),
('BND', 'Brunei Dollar', '$', 2),
('BGN', 'Bulgarian Lev', 'лв', 2),
('BIF', 'Burundian Franc', 'FBu', 0),
('KHR', 'Cambodian Riel', '៛', 2),
('CAD', 'Canadian Dollar', '$', 2),
('CVE', 'Cape Verde Escudo', '$', 2),
('XAF', 'Central African CFA', 'FCFA', 0),
('CLP', 'Chilean Peso', '$', 0),
('CNY', 'Chinese Yuan Renminbi', '¥', 2),
('COP', 'Colombian Peso', '$', 2),
('KMF', 'Comorian Franc', 'CF', 0),
('CDF', 'Congolese franc', 'FC', 2),
('CRC', 'Costa Rican Colon', '₡', 2),
('HRK', 'Croatian Kuna', 'kn', 2),
('CUC', 'Cuban Convertible Peso', '$', 2),
('CYP', 'Cypriot Pound', '£', 2),
('CZK', 'Czech Koruna', 'Kč', 2),
('DKK', 'Danish Krone', 'kr.', 2),
('DJF', 'Djiboutian Franc', 'Fdj', 0),
('DOP', 'Dominican Peso', 'RD$', 0),
('XCD', 'East Caribbean Dollar', '$', 2),
('EGP', 'Egyptian Pound', '£', 2),
('ERN', 'Eritrean Nakfa', 'ናቕፋ', 2),
('ETB', 'Ethiopian Birr', 'ብር', 2),
('EUR', 'European Euro', '€', 2),
('FJD', 'Fiji Dollar', '$', 2),
('GMD', 'Gambian Dalasi', 'D', 2),
('GEL', 'Georgian Lari', 'ლ', 2),
('GHC', 'Ghanaian Cedi', 'GH₵', 2),
('GTQ', 'Guatemalan Quetzal', 'Q', 2),
('GNF', 'Guinean Franc', 'FG', 0),
('GYD', 'Guyanese Dollar', '$', 2),
('HTG', 'Haitian Gourde', 'G', 2),
('HNL', 'Honduran Lempira', 'L', 2),
('HUF', 'Hungarian Forint', 'Ft', 2),
('ISK', 'Icelandic Krona', 'kr', 0),
('INR', 'Indian Rupee', '₹', 2),
('IDR', 'Indonesian Rupiah', 'Rp', 2),
('IRR', 'Iranian Rial', '﷼', 2),
('IQD', 'Iraqi Dinar', 'ع.د', 3),
('ILS', 'Israeli New Sheqel', '₪', 2),
('JMD', 'Jamaican Dollar', 'J$', 2),
('JPY', 'Japanese Yen', '¥', 0),
('JOD', 'Jordanian Dinar', 'د.ا', 3),
('KZT', 'Kazakhstani Tenge', 'лв', 2),
('KES', 'Kenyan Shilling', 'KSh,', 2),
('KRW', 'Korean Won', '₩', 0),
('KWD', 'Kuwaiti Dinar', 'د.ك', 3),
('KGS', 'Kyrgyzstani Som', 'лв', 2),
('LAK', 'Lao Kip', '₭', 2),
('LBP', 'Lebanese Pound', '£', 2),
('LSL', 'Lesotho Loti', 'L', 2),
('LRD', 'Liberian Dollar', '$', 2),
('LYD', 'Libyan Dinar', 'ل.د', 3),
('MKD', 'Macedonian Denar', 'ден', 2),
('MGA', 'Malagasy Ariary', 'Ar', 2),
('MWK', 'Malawian Kwacha', 'MK', 2),
('MYR', 'Malaysian Ringgit', 'RM', 2),
('MVR', 'Maldives Rufiyaa', 'Rf', 2),
('MRU', 'Mauritanian Ouguiya', 'UM', 2),
('MUR', 'Mauritian Rupee', '₨', 2),
('MXN', 'Mexican Peso', '$', 2),
('MDL', 'Moldovan Leu', 'L', 2),
('MNT', 'Mongolian Tugrik', '₮', 2),
('MAD', 'Moroccan Dirham', 'DH', 2),
('MZN', 'Mozambican Metical', 'MT', 2),
('MMK', 'Myanmar Kyat', 'K', 2),
('NAD', 'Namibian Dollar', '$', 2),
('NPR', 'Nepalese Rupee', '₨', 2),
('TWD', 'New Taiwan Dollar', 'NT$', 2),
('NZD', 'New Zealand Dollar', '$', 2),
('NIO', 'Nicaraguan Córdoba', 'C$', 2),
('NGN', 'Nigerian Naira', '₦', 2),
('KPW', 'North Korean Won', '₩', 2),
('NOK', 'Norwegian Krone', 'kr', 2),
('OMR', 'Omani Rial', '﷼', 3),
('PKR', 'Pakistan Rupee', '₨', 2),
('PAB', 'Panamanian Balboa', 'B/.', 2),
('PGK', 'Papua New Guinea Kina', 'K', 2),
('PYG', 'Paraguay Guarani', 'Gs', 0),
('PEN', 'Peruvian Nuevo Sol', 'S/.', 2),
('PHP', 'Philippine Peso', '₱', 2),
('PLN', 'Polish Zloty', 'zł', 2),
('QAR', 'Qatari Riyal', '﷼', 2),
('RON', 'Romanian Leu', 'lei', 2),
('RUB', 'Russian Ruble', '₽', 2),
('RWF', 'Rwandan Franc', 'FRw', 0),
('WST', 'Samoan Tala', 'WS$', 2),
('STN', 'Sao Tome Dobra', 'Db', 2),
('SAR', 'Saudi Arabian Riyal', '﷼', 2),
('RSD', 'Serbian Dinar', 'Дин.', 2),
('SCR', 'Seychelles Rupee', '₨', 2),
('SLL', 'Sierra Leonean Leone', 'Le', 2),
('SGD', 'Singapore Dollar', '$', 2),
('SBD', 'Solomon Islands Dollar', '$', 2),
('SOS', 'Somali Shilling', 'S', 2),
('ZAR', 'South African Rand', 'R', 2),
('LKR', 'Sri Lankan Rupee', 'රු', 2),
('SSP', 'Sudanese pound', '£', 2),
('SRD', 'Suriname Dollar', '$', 2),
('SZL', 'Swazi Lilangeni', 'E', 2),
('SEK', 'Swedish Krona', 'kr', 2),
('CHF', 'Swiss Franc', 'CHF', 2),
('SYP', 'Syrian Pound', '£', 2),
('TJS', 'Tajikistan Somoni', 'ЅM', 2),
('TZS', 'Tanzanian Shilling', 'TSh', 2),
('THB', 'Thai Baht', '฿', 2),
('TOP', 'Tongan Pa''Anga', 'T$', 2),
('TTD', 'Trinidad and Tobago Dollar', 'TT$', 2),
('TND', 'Tunisian Dinar', 'د.ت', 3),
('TRY', 'Turkish New Lira', '₺', 2),
('TMT', 'Turkmenistan New Manat', 'T', 2),
('UGX', 'Ugandan Shilling', 'USh', 0),
('UAH', 'Ukrainian Hryvnia', '₴', 2),
('AED', 'United Arab Emirates Dirham', 'د.إ', 2),
('GBP', 'United Kingdom Pound Sterling', '£', 2),
('USD', 'United States Dollar', '$', 2),
('UYU', 'Uruguayan peso', '$U', 2),
('UZS', 'Uzbekistani Som', 'лв', 2),
('VUV', 'Vanuatu Vatu', 'VT', 0),
('VES', 'Venezuelan Bolivar', 'Bs', 2),
('VND', 'Viet Nam Dong', '₫', 0),
('XOF', 'West African CFA', 'CFA', 0),
('YER', 'Yemeni Rial', '﷼', 2),
('ZMW', 'Zambian Kwacha', 'ZK', 2),
('ZWL', 'Zimbabwean Dollar', '$', 2);


-- +goose Down
DELETE FROM currencies WHERE code IN (
'AFN',
'ALL',
'DZD',
'AOA',
'ARS',
'AMD',
'AUD',
'AZN',
'BSD',
'BHD',
'BDT',
'BBD',
'BYN',
'BZD',
'BTN',
'BOB',
'BAM',
'BWP',
'BRL',
'BND',
'BGN',
'BIF',
'KHR',
'CAD',
'CVE',
'XAF',
'CLP',
'CNY',
'COP',
'KMF',
'CDF',
'CRC',
'HRK',
'CUC',
'CYP',
'CZK',
'DKK',
'DJF',
'DOP',
'XCD',
'EGP',
'ERN',
'ETB',
'EUR',
'FJD',
'GMD',
'GEL',
'GHC',
'GTQ',
'GNF',
'GYD',
'HTG',
'HNL',
'HUF',
'ISK',
'INR',
'IDR',
'IRR',
'IQD',
'ILS',
'JMD',
'JPY',
'JOD',
'KZT',
'KES',
'KRW',
'KWD',
'KGS',
'LAK',
'LBP',
'LSL',
'LRD',
'LYD',
'MKD',
'MGA',
'MWK',
'MYR',
'MVR',
'MRU',
'MUR',
'MXN',
'MDL',
'MNT',
'MAD',
'MZN',
'MMK',
'NAD',
'NPR',
'TWD',
'NZD',
'NIO',
'NGN',
'KPW',
'NOK',
'OMR',
'PKR',
'PAB',
'PGK',
'PYG',
'PEN',
'PHP',
'PLN',
'QAR',
'RON',
'RUB',
'RWF',
'WST',
'STN',
'SAR',
'RSD',
'SCR',
'SLL',
'SGD',
'SBD',
'SOS',
'ZAR',
'LKR',
'SSP',
'SRD',
'SZL',
'SEK',
'CHF',
'SYP',
'TJS',
'TZS',
'THB',
'TOP',
'TTD',
'TND',
'TRY',
'TMT',
'UGX',
'UAH',
'AED',
'GBP',
'USD',
'UYU',
'UZS',
'VUV',
'VES',
'VND',
'XOF',
'YER',
'ZMW',
'ZWL'
);