import type { Channel, ChannelMessage } from './types';

export let memebersData = [
	{
		name: 'Ethan Caldwell',
		title: 'Full Stack Developer',
		image: 'https://images.pexels.com/photos/6942776/pexels-photo-6942776.jpeg'
	},
	{
		name: 'Olivia Hart',
		title: 'Software Architect',
		image:
			'https://images.pexels.com/photos/27603433/pexels-photo-27603433/free-photo-of-blonde-beauty-s-eye-catching-glasses.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'
	},
	{
		name: 'Matthew Wilcher',
		title: 'Database Administrator',
		image:
			'https://images.pexels.com/photos/7752805/pexels-photo-7752805.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'
	},
	{
		name: 'Lucas Barrett',
		title: 'Client',
		image:
			'https://images.pexels.com/photos/2341350/pexels-photo-2341350.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1'
	}
];
export let messageData: ChannelMessage[] = [
	{
		id: 1,
		type: 'USER',
		name: 'Lucas Barrett',
		title: 'Client',
		date: new Date().toLocaleString(),
		image:
			'https://images.pexels.com/photos/2341350/pexels-photo-2341350.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		message:
			"Hey everyone, thanks again for all the work. Just checking — are we on track for Friday's delivery?"
	},
	{
		id: 2,
		type: 'USER',
		name: 'Ethan Caldwell',
		title: 'Full Stack Developer',
		date: new Date().toLocaleString(),
		image: 'https://images.pexels.com/photos/6942776/pexels-photo-6942776.jpeg',
		message:
			"Hey Lucas, yes — the frontend is nearly complete. I’ve hooked up most components and I'm finalizing the API integration today."
	},
	{
		id: 3,
		type: 'FILE_UPLOAD',
		date: new Date().toLocaleString(),
		message: 'Ethan Caldwell uploaded a file: — Technical-Specs-v2.pdf',
		link: '/'
	},
	{
		id: 4,
		type: 'USER',
		name: 'Olivia Hart',
		title: 'Software Architect',
		date: new Date().toLocaleString(),
		image:
			'https://images.pexels.com/photos/27603433/pexels-photo-27603433/free-photo-of-blonde-beauty-s-eye-catching-glasses.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		message:
			'Thanks for the upload, Ethan. I’ll review the specs now. Also, let’s ensure the dashboard can handle increased traffic — especially since we’ll be demoing it next week.'
	},
	{
		id: 5,
		type: 'QUOTE',
		date: new Date().toLocaleString(),
		message: 'Quotation #4821 has been issued — Amount: $1,200'
	},
	{
		id: 6,
		type: 'USER',
		name: 'Lucas Barrett',
		title: 'Client',
		date: new Date().toLocaleString(),
		image:
			'https://images.pexels.com/photos/2341350/pexels-photo-2341350.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		message:
			'Got the quote — looks good on my end. Once the invoice is ready, I’ll process payment.'
	},
	{
		id: 7,
		type: 'USER',
		name: 'Matthew Wilcher',
		title: 'Database Administrator',
		date: new Date().toLocaleString(),
		image:
			'https://images.pexels.com/photos/7752805/pexels-photo-7752805.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		message:
			'Great. I’ve optimized the data pipeline and prepped the schema for analytics logging. Ethan, I noticed one of your queries is pulling large joins — let’s sync later to improve that.'
	},
	{
		id: 8,
		type: 'INVOICE',
		date: new Date().toLocaleString(),
		message: 'Invoice #5183 has been issued — Amount: $1,200'
	},

	{
		id: 9,
		type: 'USER',
		name: 'Olivia Hart',
		title: 'Software Architect',
		date: new Date().toLocaleString(),
		image:
			'https://images.pexels.com/photos/27603433/pexels-photo-27603433/free-photo-of-blonde-beauty-s-eye-catching-glasses.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		message:
			'Invoice just came through. Thanks, team. Once Lucas confirms payment, we can schedule deployment for staging.'
	},
	{
		id: 10,
		type: 'USER',
		name: 'Lucas Barrett',
		title: 'Client',
		date: new Date().toLocaleString(),
		image:
			'https://images.pexels.com/photos/2341350/pexels-photo-2341350.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1',
		message: 'Confirmed — payment will be processed today. Looking forward to the demo!'
	}
];
export let channelData: Channel[] = [
	{
		id: 1,
		name: 'general',
		projectId: null
	},
	{
		id: 2,
		name: 'Web Project',
		projectId: 1
	},
	{
		id: 3,
		name: 'Advertising Campaign',
		projectId: 2
	}
];

export const phrases = [
	'Nice to meet you.',
	'What do you think about this?',
	"That's a good one!",
	'Really? Tell me more about it!',
	"Frankly speaking, I think that's interesting.",
	"Well, to be honest with you, I wasn't sure at first.",
	'Sure, no problem!',
	"Never mind, it's fine!",
	'Never mind, forget what I just said.',
	'How is it going?',
	'Long time no see!',
	'What have you been up to?',
	"Can't complain.",
	'How do you know?',
	'It is very kind of you!',
	'Thank you anyway.',
	'Thank you in advance.',
	'No worries!',
	"What's going on?",
	'Did I get you right?',
	"Don't take it to heart.",
	"I didn't catch the last word.",
	"Sorry, I wasn't listening.",
	"It doesn't matter.",
	'Fingers crossed.',
	'Oh, that. That explains it.',
	'Things happen.',
	'Sorry to bother you.',
	"I'll be with you in a minute.",
	'Where were you?',
	'You were saying?',
	'Lucky you!',
	'I freaked out!',
	'Good for you!',
	"You've got to be kidding me!",
	'Cheer up!',
	'Come on, you can do it!',
	'Keep up the good work!',
	"That's lit!",
	'There you go!',
	'Not a bit.',
	'There is no room for doubt.',
	"I'll text you!",
	"It's not worth it!",
	'You rock!',
	'You should go the extra mile.',
	'Step up your game.',
	'Pull yourself together.',
	'You sold me!',
	"Couldn't care less.",
	'This is a no-brainer.',
	'I screwed up!',
	'Can you cover me?',
	"I'd better be going!",
	'Take care!',
	"Thank heavens it's Friday!",
	'Hey, how are you doing today?',
	'Can you tell me more about that?',
	'I really resonate with that.',
	'That sounds really tough.',
	"I can see where you're coming from.",
	'Would you like to share more?',
	'Are you comfortable sharing more?',
	'I demand details!',
	'Tell me more about your experience.',
	'How did that make you feel?',
	"That's so true!",
	'I 100% agree with you.',
	'Exactly!',
	'Absolutely!',
	"That's so right!",
	"You're so right.",
	"You're right.",
	"I didn't expect that!",
	'What happened next?',
	'Can you explain that a bit more?',
	'How can I help you?',
	"Is there anything else you'd like to add?",
	'Thanks for sharing that with me.',
	'I appreciate your honesty.',
	"Let's keep this conversation going.",
	'What do you think we should do?',
	'Have you considered other options?',
	"That's an interesting point.",
	"I hadn't thought of it that way.",
	'Could you clarify that for me?',
	'What do you mean by that?',
	'How do you feel about that?',
	"Let's talk about something else.",
	'What are your plans for the weekend?',
	'Do you have any hobbies?',
	'I love hearing your thoughts.',
	'Thanks for your patience.',
	'Sorry for the delay.',
	'No problem at all.',
	"That's okay, take your time.",
	"I'm here if you need me.",
	'Feel free to ask me anything.',
	'Is there something specific you want to discuss?',
	"Let's get back to that later.",
	"I'm glad you brought that up.",
	'Thanks for letting me know.',
	'I hope that helps.',
	'Let me know if you have any questions.',
	'Looking forward to hearing from you.',
	'Have a great day!',
	'Talk to you soon!',
	'Bye for now!',
	'Can you please elaborate on that?',
	"I completely understand where you're coming from.",
	'That sounds like a great idea!',
	'Could you please clarify your point?',
	"I'm not quite sure I follow you.",
	'Thanks for bringing that to my attention.',
	'Let me know if you need any assistance.',
	'I appreciate your feedback on this matter.',
	'Sorry, I didn’t mean to interrupt.',
	'What would you like to talk about today?',
	'I’m here to help whenever you need me.',
	'That’s a fantastic suggestion!',
	'How can I make this easier for you?',
	'I’m looking forward to your reply.',
	'Please feel free to reach out anytime.',
	'Could you give me some more details?',
	'I’m happy to discuss this further.',
	'That’s really interesting, tell me more!',
	'I’m glad you shared that with me.',
	'Do you have any other questions?',
	'Let’s work through this together.',
	'I’m not sure I understand completely.',
	'Can you help me understand your perspective?',
	'Thanks for your patience while I check.',
	'I’ll get back to you as soon as possible.',
	'Is there anything else I can do for you?',
	'I appreciate your honesty and openness.',
	'That’s a valid point you’ve made.',
	'What are your thoughts on this matter?',
	'Could you please repeat that?',
	'I’m sorry, I didn’t catch that.',
	'Let me confirm that for you.',
	'I’ll keep you updated on the progress.',
	'Thanks for your cooperation.',
	'I’m here if you want to talk more.',
	'That’s definitely something to consider.',
	'I’m glad we had this chat.',
	'Feel free to share your ideas anytime.',
	'I understand how you feel about that.',
	'Thanks for being so understanding.',
	'I’m sorry for any inconvenience caused.',
	'Let’s take it one step at a time.',
	'I’m excited to hear more about it.',
	'That’s a great question!',
	'Let’s dive deeper into this topic.',
	'I appreciate you taking the time to explain.',
	'What would you like me to do next?',
	'I’m here to support you.',
	'Thanks for your valuable input.',
	'I’m happy to help with that.',
	'Could you please provide an example?',
	'I’m not sure, but I’ll find out for you.',
	'That’s a good point to keep in mind.',
	'Let me know if you want to discuss this later.',
	'I’ll do my best to assist you.',
	'Thanks for your quick response.',
	'I hope this information is helpful.',
	'Let’s keep the conversation going.',
	'I’m looking forward to working with you.',
	'Please don’t hesitate to ask.',
	'That’s very helpful, thank you!',
	'I’m glad you brought that up.',
	'I’m here to listen.',
	'Thanks for your understanding.',
	'I appreciate you sharing your thoughts.',
	'Let’s figure this out together.',
	'I’m sorry, I didn’t mean to confuse you.',
	'Could you please be more specific?',
	'I’m happy to clarify anything you need.',
	'That sounds like a plan.',
	'I’m here whenever you need me.',
	'Thanks for your continued support.',
	'I’ll make sure to follow up on that.',
	'Please keep me posted.',
	'I’m eager to hear your opinion.',
	'Let me know how I can improve.',
	'Thanks for pointing that out.',
	'I’m glad we’re on the same page.',
	'I appreciate your time and effort.',
	'Let’s schedule a time to talk more.',
	'I’m here to answer any questions.',
	'Thanks for your detailed explanation.',
	'I hope you have a wonderful day!',
	'Please take your time.',
	'I’m always happy to chat.',
	'Thanks for trusting me with this.',
	'I’m looking forward to our next conversation.',
	'Let me know if anything changes.',
	'I’m here to make things easier for you.',
	'Thanks for your kind words.',
	'I’ll be here if you need anything else.',
	'Let’s keep in touch.',
	'That’s a very insightful comment.',
	'I appreciate your perspective.',
	'I’m happy to continue this discussion.',
	'Thanks for being so cooperative.',
	'I’ll get right on that.',
	'Please let me know if you have concerns.',
	'I’m glad to assist you anytime.',
	'Thanks for your great attitude.',
	'I’m here to ensure you have a good experience.',
	'Let me know if you want me to explain further.',
	'I’m always here to listen.',
	'Thanks for your enthusiasm!',
	'I appreciate your willingness to help.',
	'Let’s make this happen together.'
];
