-- +goose Up
CREATE TABLE projects (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    status BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (status) REFERENCES project_statuses(id) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_projects_name ON projects(name);


-- +goose Down
DROP INDEX IF EXISTS idx_projects_name;
DROP TABLE IF EXISTS projects;
